platform :ios, '11.0'
use_frameworks!
inhibit_all_warnings!

target "DiaryProject" do
	pod 'SnapKit'
	pod 'RealmSwift'

  target :DiaryProjectTests do
    inherit! :search_paths
    pod 'Nimble', '~> 7.0.0'
  end
end
